
APP =part2
# I am a comment, and I want to say that the variable CC will be
# # the compiler to use.
CC=gcc
# # Hey!, I am comment number 2. I want to say that CFLAGS will be the
# # options I'll pass to the compiler.
CFLAGS=-c 

all:     
	$(CC) -o $(APP) main2_1.c -lpthread 
p1:     
	$(CC) -o $(APP) main2_1.c -lpthread 
p2:     
	$(CC) -o $(APP) main2_2.c -lpthread 
p3:     
	$(CC) -o $(APP) main2_3.c -lpthread 
p4:     
	$(CC) -o $(APP) main2_4.c -lpthread 
clean:
	rm -f $(APP)
	rm -rf *.o

