
APP =part1
# I am a comment, and I want to say that the variable CC will be
# # the compiler to use.
CC=gcc
# # Hey!, I am comment number 2. I want to say that CFLAGS will be the
# # options I'll pass to the compiler.
CFLAGS=-c 

all:     
	$(CC) -o $(APP) main1.c -lpthread 
clean:
	rm -f $(APP)
	rm -rf *.o

